---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  # $(echo -n 'ChangeThisSuperSecretPassword' | base64)
  mariadb-root-password: <your-mariadb-root-password>
  # $(echo -n 'ChangeThisToWordpress-user' | base64)
  mariadb-user: <your-mariadb-user>
  # $(echo -n 'ChangeThisSuperSecretPassword' | base64)
  mariadb-password: <your-mariadb-password>
