---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  # Use the following command to generate a random password:
  # echo -n 'ChangeThisSuperSecretPassword' | base64
  mariadb-root-password: <your-mariadb-root-password>
  mariadb-password: <your-mariadb-password>
