---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  # Use the following command to generate a random password:
  # echo -n 'ChangeThisSuperSecretPassword' | base64
  wordpress-user-password: <your-wordpress-user-password>
  # Use the following command to generate your wordpress user:
  # echo -n 'wordpressuser' | base64
  wordpress-username: <your-wordpress-username>
