---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  # $(echo -n 'ChangeThisSuperSecretPassword' | base64)
  wordpress-user-password: <your-wordpress-user-password>
